services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: x
      POSTGRES_PASSWORD: x
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    networks:
      - app

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app

  backend:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:
