spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat_db
    username: ${POSTGRESQL_USERNAME:x}
    password: ${POSTGRESQL_PASSWORD:x}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: "*"
