spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB_NAME:chat_db}
    username: ${POSTGRESQL_USERNAME:x}
    password: ${POSTGRESQL_PASSWORD:x}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: ${JWT_SECRET:secret}

swagger:
  url: ${server_url:http://localhost:8080}

server:
  servlet:
    context-path: /
